repos:
  - repo: local
    hooks:
      - id: format-icon-data
        name: Format icon data
        entry: npm run format:icondata
        language: system
        pass_filenames: false
        files:
          glob:
            - data/simple-icons.json
      - id: prettier
        name: Prettier
        entry: npm run prettier -- --write
        language: system
        pass_filenames: false
      - id: xo
        name: XO
        entry: npx xo --fix
        language: system
        pass_filenames: false
        types: [javascript]
      - id: ourlint
        name: Our lint
        language: system
        entry: node scripts/lint/ourlint.js
        pass_filenames: false
        always_run: true
      - id: jsonlint
        name: JSON Lint
        entry: node scripts/lint/jsonlint.js
        pass_filenames: false
        language: system
        types: [json]
      - id: svglint
        name: SVG Lint
        entry: npx svglint --ci --config svglint.config.mjs --git-changed
        pass_filenames: false
        language: system
        types: [svg]
        files:
          glob:
            - icons/*.svg
        verbose: true
        stages: [commit]
      - id: markdownlint
        name: Markdownlint
        entry: "npx markdownlint-cli2 '**/*.md' '#node_modules'"
        pass_filenames: false
        types: [markdown]
        language: system
