language: node_js
node_js:
  - "6"

script:
  - npm run jsonlint
  - jekyll build

notifications:
  email:
    on_success: never
    on_failure: change

deploy:
  provider: npm
  email: "johanringmann@gmail.com"
  api_key: "$NPM_KEY"
  on:
    branch: master
