jobs:
  include:
    - stage: "Test"
      name: "Lint"
      language: node_js
      node_js: 8
      script:
        - npm run jsonlint
        - npm run svglint
        - npm run wslint
    - name: "Build website"
      language: ruby
      rvm: 2.4.1
      install:
        - gem install jekyll
      script:
        - jekyll build
    - name: "Test package"
      language: node_js
      node_js: 8
      script:
        - npm run test

    - stage: deploy
      name: "NPM Package"
      language: node_js
      node_js: 8
      if: branch = master

      deploy:
        provider: npm
        email: "johanringmann@gmail.com"
        api_key: "$NPM_KEY"
        on:
          branch: master
    - name: "Simple Icons Font"
      language: node_js
      node_js: 8
      before_install:
        - git clone https://github.com/simple-icons/simple-icons-font.git
        - cd simple-icons-font
      install:
        - npm install
      script:
        - npm run build

notifications:
  email:
    on_success: never
    on_failure: change
