name: Automated releases
on:
  schedule:
    # "At 00:00 on Sunday" (https://crontab.guru/once-a-week)
    - cron: "0 0 * * 0"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: simple-icons/release-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
