name: Automated releases
on:
  pull_request_review:
    types: [submitted]
  schedule:
    # "At 00:00 on Sunday" (https://crontab.guru/once-a-week)
    - cron: "0 0 * * 0"

jobs:
  release:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request_review' && contains(github.event.pull_request.labels.*.name, 'release')) || github.event_name == 'schedule'
    steps:
    - uses: simple-icons/release-action@master
      with:
        repo-token: ${{ secrets.RELEASE_TOKEN }}
