name: Sync GitHub labels

on:
  push:
    paths:
      - '.github/labels.yml'
    branches:
      - develop
  label:
    types: [created, edited, deleted]
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode (no changes applied)'
        required: false
        default: false
        type: boolean
      skip-delete:
        description: 'Skip deleting labels that are not in the labels.yml file'
        required: false
        default: false
        type: boolean

jobs:
  labels:
    # Avoid infinite loop by ignoring actions triggered by the bot itself
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Block manual label changes
        if: github.event_name == 'label'
        run: |
          echo "‚ùå Labels must be modified via .github/labels.yml. Restoring..."
      - uses: actions/checkout@v4
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: ${{ inputs.skip-delete || false }}
          dry-run: ${{ inputs.dry-run || false }}
